grandfather(X,Z):-parent(X,Y),parent(Y,Z),male(X).
grandmother(P,R):-parent(P,Q),parent(Q,R),female(P).
uncle(P,Y):-brother(P,X),father(X,Y),male(P).
uncle(P,Y):-brother(P,X),mother(X,Y),male(P).
aunt(P,Y):-sister(P,X),mother(X,Y),female(P).
aunt(P,Y):-sister(P,X),father(X,Y),female(P).
parent(moynal,mahbub).
parent(suraiya,mahbub).
parent(moynal,eyasin).
father(moynal,mahbub).
mother(syraiya,rasni).
brother(eyasin,mahbub).
brother(rasni,mahbub).
brother(biswajit,esha).
male(mahbub).
male(moynal).
male(neyaj).
female(suraiya).
female(rasni).

